version: '3'

services:
  substracker:
    container_name: substracker
    image: smhw3565/substracker:latest
    restart: unless-stopped
    ports:
      - "12122:12121"
    volumes:
      - ./1:/app/database
    environment:
      - PORT=12121
      - DB_PATH=/app/database/notifier.db
      - ENCRYPTION_KEY=change-this-to-a-random-32-character-string
      - NODE_ENV=production
      - WECHAT_API_BASE=https://qyapi.weixin.qq.com