version: '3'

services:
  wechat-notifier:
    container_name: tttt
    image: wangwangit/wangwangit:qywx
    restart: unless-stopped
    ports:
      - "12122:12121"
    volumes:
      - ./1:/app/database
    environment:
      - PORT=12121
      - DB_PATH=/app/database/notifier.db
      - ENCRYPTION_KEY=change-this-to-a-random-32-character-string
      - NODE_ENV=production
      - WECHAT_API_BASE=https://qyapi.weixin.qq.com